name: 버그 리포트
description: 버그를 제보하고 싶다면 해당 템플릿을 사용해주세요.
title: "[버그 리포트]: <버그 발생 요약>"
labels: ["bug"]
assignees:
  - alirz-pixel
  - HeejinYang
  - LikeDeer
body:
  - type: input
    id: summary
    attributes: 
      label: 한 줄 요약
      description: 버그를 간략하게 한 줄로 설명해주세요.
      placeholder: <발생한 버그 요약>
    validations:
      required: true
  - type: textarea
    id: detail
    attributes: 
      label: 상세 설명
      description: 버그에 대한 상세 설명을 적어주세요.
      placeholder: 버그에 대한 상세 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: bug
    attributes: 
      label: 버그 재현
      description: 버그를 재현할 수 있는 방법을 적어주세요.
      placeholder: "- 버그 발생 환경\n- 버그 발생 조건\n- 버그 재현 순서"
  - type: textarea
    id: more_detail
    attributes: 
      label: 추가 사항
      description: 버그에 대한 추가적인 사항이 있다면 적어주세요.
      placeholder: "- 관련 레퍼런스\n- 관련 스크린샷"