name: 기능 제안
description: 기능을 제안하고 싶다면 해당 템플릿을 사용해주세요.
title: "[기능 제안]: <제안할 기능 요약>"
labels: ["enhancement"]
assignees:
  - alirz-pixel
  - HeejinYang
  - LikeDeer
body:
  - type: input
    id: summary
    attributes: 
      label: 한 줄 요약
      description: 제안하고 싶은 기능을 간략하게 한 줄로 설명해주세요.
      placeholder: <제안할 기능 요약>
    validations:
      required: true
  - type: textarea
    id: feature_list
    attributes: 
      label: 제안 기능 리스트
      description: 제안하고 싶은 기능들에 대한 리스트를 적어주세요.
      placeholder: "- [ ] 기능 1 \n- [ ] 기능 2\n- [ ] 기능3"
      value: "- [ ] 기능 1 \n- [ ] 기능 2\n- [ ] 기능3"
    validations:
      required: true
  - type: textarea
    id: detail
    attributes: 
      label: 상세 설명
      description: 제안하신 기능에 대한 상세 설명을 적어주세요.
      placeholder: 제안하신 기능에 대한 상세 설명을 적어주세요.
      value: "기능 1: ...\n기능 2: ..."
    validations:
      required: true
  - type: textarea
    id: more_detail
    attributes: 
      label: 추가 사항
      description: 제안한 기능과 관련된 추가적인 사항이 있다면 적어주세요.
      placeholder: "- 관련 레퍼런스\n- 관련 스크린샷"